### ISSUE TITLE
black screen after update 3.32

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/org.gnome.Boxes#15]
black screen when I try to start my VMs (Fedora, Ubuntu, OpenSUSE ...)
![2019-03-12_20-24_1](https://user-images.githubusercontent.com/17401812/54243096-e1fb3300-4505-11e9-9521-e1007760b6a4.png)

Fedora 29 xfce - Nvidia 418.43 

flatpak info org.gnome.Boxes

Caixas GNOME - Máquinas virtuais e remotas simples

          ID: org.gnome.Boxes
         Ref: app/org.gnome.Boxes/x86_64/stable
        Arq.: x86_64
        Ramo: stable
     Version: 3.32.0
     License: LGPL-2.1+
      Origem: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 497,3 MB
     Runtime: org.gnome.Platform/x86_64/3.30
         Sdk: org.gnome.Sdk/x86_64/3.30

      Commit: 98dc74f7e04cfa23a0cac95e942dc4e009c2eb5828d80a009727159bc1d0e57c
         Pai: 36ce0e2c6efa0f5842f1675a157c062477d850e276ba6e35bb923ac702f0d477
     Assunto: Update usbredir repo URL (639e502a)
        Data: 2019-03-11 20:21:47 +0000
============================================================================

flatpak list --runtime
Descrição                                                                                                                              Aplicativo                                        Versão       Ramo         Arch         Origem       Installation
Locale                                                                                                                                 com.github.wwmm.pulseeffects.Locale                            stable       x86_64       flathub      system
Locale                                                                                                                                 com.google.AndroidStudio.Locale                                stable       x86_64       flathub      system
Locale                                                                                                                                 com.obsproject.Studio.Locale                                   stable       x86_64       flathub      system
Locale                                                                                                                                 com.uploadedlobster.peek.Locale                                stable       x86_64       flathub      system
Locale                                                                                                                                 fr.handbrake.ghb.Locale                                        stable       x86_64       flathub      system
Locale                                                                                                                                 io.github.GnomeMpv.Locale                                      stable       x86_64       flathub      system
Locale                                                                                                                                 net.pcsx2.PCSX2.Locale                                         stable       i386         flathub      system
Codecs                                                                                                                                 org.audacityteam.Audacity.Codecs                               stable       x86_64       flathub      system
Locale                                                                                                                                 org.audacityteam.Audacity.Locale                               stable       x86_64       flathub      system
Freedesktop.org Application Platform version 18.08 - Shared libraries provided by freedesktop.org                                      org.freedesktop.Platform                                       18.08        i386         flathub      system
Freedesktop.org Application Platform version 1.6 - Shared libraries provided by freedesktop.org                                        org.freedesktop.Platform                          1.6          1.6          x86_64       flathub      system
Freedesktop.org Application Platform version 18.08 - Shared libraries provided by freedesktop.org                                      org.freedesktop.Platform                                       18.08        x86_64       flathub      system
i386                                                                                                                                   org.freedesktop.Platform.Compat.i386                           18.08        x86_64       flathub      system
nvidia-390-59                                                                                                                          org.freedesktop.Platform.GL.nvidia-390-59                      1.4          i386         flathub      system
nvidia-390-59                                                                                                                          org.freedesktop.Platform.GL.nvidia-390-59                      1.4          x86_64       flathub      system
nvidia-396-54                                                                                                                          org.freedesktop.Platform.GL.nvidia-396-54                      1.4          x86_64       flathub      system
nvidia-410-66                                                                                                                          org.freedesktop.Platform.GL.nvidia-410-66                      1.4          i386         flathub      system
nvidia-410-66                                                                                                                          org.freedesktop.Platform.GL.nvidia-410-66                      1.4          x86_64       flathub      system
nvidia-410-73                                                                                                                          org.freedesktop.Platform.GL.nvidia-410-73                      1.4          i386         flathub      system
nvidia-410-73                                                                                                                          org.freedesktop.Platform.GL.nvidia-410-73                      1.4          x86_64       flathub      system
nvidia-410-78                                                                                                                          org.freedesktop.Platform.GL.nvidia-410-78                      1.4          i386         flathub      system
nvidia-410-78                                                                                                                          org.freedesktop.Platform.GL.nvidia-410-78                      1.4          x86_64       flathub      system
nvidia-415-18                                                                                                                          org.freedesktop.Platform.GL.nvidia-415-18                      1.4          i386         flathub      system
nvidia-415-18                                                                                                                          org.freedesktop.Platform.GL.nvidia-415-18                      1.4          x86_64       flathub      system
nvidia-415-25                                                                                                                          org.freedesktop.Platform.GL.nvidia-415-25                      1.4          i386         flathub      system
nvidia-415-25                                                                                                                          org.freedesktop.Platform.GL.nvidia-415-25                      1.4          x86_64       flathub      system
nvidia-415-27                                                                                                                          org.freedesktop.Platform.GL.nvidia-415-27                      1.4          i386         flathub      system
nvidia-415-27                                                                                                                          org.freedesktop.Platform.GL.nvidia-415-27                      1.4          x86_64       flathub      system
nvidia-418-43                                                                                                                          org.freedesktop.Platform.GL.nvidia-418-43                      1.4          i386         flathub      system
nvidia-418-43                                                                                                                          org.freedesktop.Platform.GL.nvidia-418-43                      1.4          x86_64       flathub      system
nvidia-410-73                                                                                                                          org.freedesktop.Platform.GL32.nvidia-410-73                    1.4          x86_64       flathub      system
nvidia-410-78                                                                                                                          org.freedesktop.Platform.GL32.nvidia-410-78                    1.4          x86_64       flathub      system
nvidia-415-18                                                                                                                          org.freedesktop.Platform.GL32.nvidia-415-18                    1.4          x86_64       flathub      system
nvidia-415-25                                                                                                                          org.freedesktop.Platform.GL32.nvidia-415-25                    1.4          x86_64       flathub      system
nvidia-415-27                                                                                                                          org.freedesktop.Platform.GL32.nvidia-415-27                    1.4          x86_64       flathub      system
nvidia-418-43                                                                                                                          org.freedesktop.Platform.GL32.nvidia-418-43                    1.4          x86_64       flathub      system
Adwaita icon theme - Adwaita icon theme                                                                                                org.freedesktop.Platform.Icontheme.Adwaita                     1.0          x86_64       flathub      system
FFmpeg extension - Add support for aac, mpeg4 and h264                                                                                 org.freedesktop.Platform.ffmpeg                                1.6          x86_64       flathub      system
html5-codecs                                                                                                                           org.freedesktop.Platform.html5-codecs                          18.08        i386         flathub      system
html5-codecs                                                                                                                           org.freedesktop.Platform.html5-codecs                          18.08        x86_64       flathub      system
Locale                                                                                                                                 org.gnome.Boxes.Locale                                         stable       x86_64       flathub      system
Locale                                                                                                                                 org.gnome.Lollypop.Locale                                      stable       x86_64       flathub      system
GNOME Application Platform version 3.26 - Shared libraries used by GNOME applications                                                  org.gnome.Platform                                             3.26         x86_64       flathub      system
GNOME Application Platform version 3.28 - Shared libraries used by GNOME applications                                                  org.gnome.Platform                                             3.28         x86_64       flathub      system
GNOME Application Platform version 3.30 - Shared libraries used by GNOME applications                                                  org.gnome.Platform                                             3.30         x86_64       flathub      system
GNOME Software Development Kit version 3.30 - Tools and headers for developing applications using the GNOME application platform       org.gnome.Sdk                                                  3.30         x86_64       flathub      system
Docs                                                                                                                                   org.gnome.Sdk.Docs                                             3.30         x86_64       flathub      system
Locale                                                                                                                                 org.gnome.font_viewer.Locale                                   stable       x86_64       flathub      system
Adapta Gtk+ theme - Adapta Gtk+ theme                                                                                                  org.gtk.Gtk3theme.Adapta                                       3.22         x86_64       flathub      system
Arc Gtk theme - Arc Gtk theme                                                                                                          org.gtk.Gtk3theme.Arc                                          3.22         x86_64       flathub      system
Arc-Dark Gtk theme - Arc-Dark Gtk theme                                                                                                org.gtk.Gtk3theme.Arc-Dark                                     3.22         x86_64       flathub      system
Yaru-dark Gtk Theme - Yaru-dark theme                                                                                                  org.gtk.Gtk3theme.Yaru-dark                                    3.22         x86_64       flathub      system
Adwaita theme - Adwaita widget theme matching the GNOME adwaita theme                                                                  org.kde.KStyle.Adwaita                                         5.12         x86_64       flathub      system
KDE Application Platform - Shared libraries used by KDE applications                                                                   org.kde.Platform                                               5.12         x86_64       flathub      system
Locale                                                                                                                                 org.libreoffice.LibreOffice.Locale                             stable       x86_64       flathub      system
Locale                                                                                                                                 org.videolan.VLC.Locale                                        stable       x86_64       flathub      system

=========================================================================

flatpak run org.gnome.Boxes

(gnome-boxes:2): Gtk-WARNING **: 19:26:32.954: GtkFlowBox with a model will ignore sort and filter functions

(gnome-boxes:2): Gtk-WARNING **: 19:26:32.955: GtkListBox with a model will ignore sort and filter functions

(gnome-boxes:2): Boxes-CRITICAL **: 19:26:33.038: media-manager.vala:224: Error connecting to Tracker: Failed to load SPARQL backend: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Tracker1 was not provided by any .service files
libEGL warning: DRI2: failed to authenticate

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.329: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.329: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.329: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.329: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.343: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.343: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.353: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.353: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.381: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.381: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.399: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.399: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.410: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 19:26:46.410: update_area: assertion 'so != NULL' failed

**Comment by felipeborges** [comment]
Seems like a nvidia driver issue. Could you please paste here the output of `flatpak --gl-drivers`?

**Comment by FastOSlinux** [comment]
works with 3.30..

[fedora26ssd@localhost ~]$ flatpak --gl-drivers
nvidia-418-43
default
host
=======================

LIBGL_DEBUG=verbose flatpak run org.gnome.Boxes//stable"

(gnome-boxes:2): Gtk-WARNING **: 17:30:16.492: GtkFlowBox with a model will ignore sort and filter functions

(gnome-boxes:2): Gtk-WARNING **: 17:30:16.493: GtkListBox with a model will ignore sort and filter functions

(gnome-boxes:2): Boxes-CRITICAL **: 17:30:16.573: media-manager.vala:224: Error connecting to Tracker: Failed to load SPARQL backend: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Tracker1 was not provided by any .service files
libEGL war.ning: DRI2: failed to authenticate
libGL: Can't open configuration file /etc/drirc: Arquivo ou diretório inexistente.
libGL: Warning in /home/fedora26ssd/.drirc line 1, column 0: <device> should be inside <driconf>.
libGL: Can't open configuration file /etc/drirc: Arquivo ou diretório inexistente.
libGL: Warning in /home/fedora26ssd/.drirc line 1, column 0: <device> should be inside <driconf>.

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:25.986: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:25.986: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:25.986: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:25.986: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:26.001: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:26.001: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:26.017: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:26.017: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:26.060: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:26.060: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:26.085: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:26.085: update_area: assertion 'so != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:26.100: spice_display_widget_gl_scanout: assertion 'scanout != NULL' failed

(gnome-boxes:2): GSpice-CRITICAL **: 17:30:26.100: update_area: assertion 'so != NULL' failed

**Comment by felipehw** [comment]
Same here.

Everything was fine before 3.32.

I'm running a Fedora 29 with bumblebee BUT without using Nvidia for Gnome Boxes (i'm not using `optirun`). The Gnome Boxes is running at the top of  *Intel® Haswell Mobile*.

![Screenshot from 2019-03-14 09-17-44](https://user-images.githubusercontent.com/4523897/54356307-0ce6a380-463a-11e9-8955-7ec07048274f.png)

--------------------------------------------------------------------------------------------------------------------------------

- `$ flatpak info org.gnome.Boxes`:
```
GNOME Boxes - Simple remote and virtual machines

          ID: org.gnome.Boxes
         Ref: app/org.gnome.Boxes/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.32.0
     License: LGPL-2.1+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 497,3 MB
     Runtime: org.gnome.Platform/x86_64/3.30
         Sdk: org.gnome.Sdk/x86_64/3.30

      Commit: 98dc74f7e04cfa23a0cac95e942dc4e009c2eb5828d80a009727159bc1d0e57c
      Parent: 36ce0e2c6efa0f5842f1675a157c062477d850e276ba6e35bb923ac702f0d477
     Subject: Update usbredir repo URL (639e502a)
        Date: 2019-03-11 20:21:47 +0000
```
--------------------------------------------------------------------------------------------------------------------------------
- `flatpak list --runtime`:
```
Description            Application    Version Branch Arch   Origin  Installation
Locale                 …editor.Locale         stable x86_64 flathub system
Locale                 …latype.Locale         stable x86_64 flathub system
Locale                 …rktext.Locale         stable x86_64 flathub system
Locale                 …lyrics.Locale         stable x86_64 flathub system
Locale                 …Snes9x.Locale         stable x86_64 flathub system
Locale                 …mebank.Locale         stable x86_64 flathub user
Locale                 …ke.ghb.Locale         stable x86_64 flathub system
Locale                 …dLibet.Locale         stable x86_64 flathub system
Locale                 …gaupol.Locale         stable x86_64 flathub system
Locale                 …redict.Locale         stable x86_64 flathub system
Locale                 …color3.Locale         stable x86_64 flathub system
Locale                 …in_emu.Locale         stable x86_64 flathub system
Codecs                 …dacity.Codecs         stable x86_64 flathub system
Locale                 …dacity.Locale         stable x86_64 flathub system
Locale                 …ktable.Locale         stable x86_64 flathub system
Freedesktop.org Appli… …ktop.Platform 1.6     1.6    x86_64 flathub system
Freedesktop.org Appli… …ktop.Platform         18.08  x86_64 flathub system
Freedesktop.org Appli… …ktop.Platform         18.08  x86_64 flathub user
i386                   …m.Compat.i386         18.08  x86_64 flathub system
nvidia-410-73          …nvidia-410-73         1.4    x86_64 flathub system
nvidia-410-73          …nvidia-410-73         1.4    x86_64 flathub user
nvidia-410-73          …nvidia-410-73         1.4    x86_64 flathub system
Adwaita icon theme - … …theme.Adwaita         1.0    x86_64 flathub system
Intel VAAPI Driver - … …m.VAAPI.Intel         1.6    x86_64 flathub system
Intel                  …m.VAAPI.Intel         18.08  x86_64 flathub system
Intel                  …m.VAAPI.Intel         18.08  x86_64 flathub user
FFmpeg extension - Ad… …atform.ffmpeg         1.6    x86_64 flathub system
html5-codecs           ….html5-codecs         18.08  x86_64 flathub system
html5-codecs           ….html5-codecs         18.08  x86_64 flathub user
Freedesktop.org Softw… …eedesktop.Sdk 1.6     1.6    x86_64 flathub system
Freedesktop.org Softw… …eedesktop.Sdk         18.08  x86_64 flathub system
Locale                 ….Boxes.Locale         stable x86_64 flathub user
Locale                 …ulator.Locale         stable x86_64 flathub system
Locale                 …lendar.Locale         stable x86_64 flathub system
Locale                 …acters.Locale         stable x86_64 flathub system
Locale                 …Viewer.Locale         stable x86_64 flathub system
Locale                 …Evince.Locale         stable x86_64 flathub system
Locale                 …ractal.Locale         stable x86_64 flathub system
Locale                 ….Games.Locale         stable x86_64 flathub system
Locale                 ….Geary.Locale         stable x86_64 flathub system
Locale                 …rdSafe.Locale         stable x86_64 flathub system
GNOME Application Pla… …nome.Platform         3.26   x86_64 flathub system
GNOME Application Pla… …nome.Platform         3.28   x86_64 flathub system
GNOME Application Pla… …nome.Platform         3.30   x86_64 flathub system
Locale                 …Polari.Locale         stable x86_64 flathub system
GNOME Software Develo… org.gnome.Sdk          3.28   x86_64 flathub system
GNOME Software Develo… org.gnome.Sdk          3.30   x86_64 flathub system
Docs                   …nome.Sdk.Docs         3.30   x86_64 flathub system
Locale                 …corder.Locale         stable x86_64 flathub system
Codecs                 ….Totem.Codecs         stable x86_64 flathub system
Locale                 ….Totem.Locale         stable x86_64 flathub system
Locale                 …eather.Locale         stable x86_64 flathub system
Locale                 …clocks.Locale         stable x86_64 flathub system
Locale                 …me.eog.Locale         stable x86_64 flathub system
Locale                 …viewer.Locale         stable x86_64 flathub system
Locale                 ….gedit.Locale         stable x86_64 flathub system
Locale                 …e.ghex.Locale         stable x86_64 flathub system
Locale                 …e.gitg.Locale         stable x86_64 flathub system
Locale                 …e.meld.Locale         stable x86_64 flathub system
Locale                 …podder.Locale         stable x86_64 flathub system
Locale                 …kscape.Locale         stable x86_64 flathub system
Adwaita theme - Adwai… …Style.Adwaita         5.11   x86_64 flathub system
Adwaita theme - Adwai… …Style.Adwaita         5.12   x86_64 flathub system
KDE Application Platf… ….kde.Platform         5.11   x86_64 flathub system
KDE Application Platf… ….kde.Platform         5.12   x86_64 flathub system
QGnomePlatform - Qt P… …GnomePlatform         5.11   x86_64 flathub system
QGnomePlatform - Qt P… …GnomePlatform         5.12   x86_64 flathub system
Locale                 …enlive.Locale         stable x86_64 flathub system
Locale                 …okular.Locale         stable x86_64 flathub system
Locale                 …Office.Locale         stable x86_64 flathub system
Locale                 …Picard.Locale         stable x86_64 flathub system
Locale                 …an.VLC.Locale         stable x86_64 flathub system
```
--------------------------------------------------------------------------------------------------------------------------------
- `LIBGL_DEBUG=verbose flatpak run org.gnome.Boxes//stable`:
```
(gnome-boxes:2): Gtk-WARNING **: 09:05:30.474: GtkFlowBox with a model will ignore sort and filter functions

(gnome-boxes:2): Gtk-WARNING **: 09:05:30.475: GtkListBox with a model will ignore sort and filter functions
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
Tracker-Message: 09:05:30.591: Could not get mtime for 'file:///home/dread/.var/app/org.gnome.Boxes/cache/tracker/meta.db': Error when getting information for file “/home/dread/.var/app/org.gnome.Boxes/cache/tracker/meta.db”: No such file or directory

(gnome-boxes:2): Tracker-WARNING **: 09:05:30.591: Falling back to bus backend, the direct backend failed to initialize: Could not open sqlite3 database:'/home/dread/.var/app/org.gnome.Boxes/cache/tracker/meta.db': unable to open database file
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/dread/.drirc: No such file or directory.
```
![Screenshot from 2019-03-14 09-05-58](https://user-images.githubusercontent.com/4523897/54355785-b9c02100-4638-11e9-816d-37ec296a351e.png)
![Screenshot from 2019-03-14 09-06-58](https://user-images.githubusercontent.com/4523897/54355789-bcbb1180-4638-11e9-89ba-8f5c01673684.png)

**Comment by felipeborges** [comment]
These are issues with the 3D acelleration that we just enabled in 3.32. I am investigating the culprit atm.

**Comment by felipehw** [comment]
The problem, at least in my case, is with preexisting boxes.
If I create a new box, everything is OK.
There is a way to use the previous flatpak while this problem exists?
Thanks :)

**Comment by felipeborges** [comment]
I filled https://gitlab.freedesktop.org/spice/spice-gtk/issues/89 where I am following up finding the culprit.

**Comment by FastOSlinux** [comment]
> The problem, at least in my case, is with preexisting boxes.
> If I create a new box, everything is OK.
> There is a way to use the previous flatpak while this problem exists?
> Thanks :)

downgrade:

sudo flatpak update --commit=36ce0e2c6efa0f5842f1675a157c062477d850e276ba6e35bb923ac702f0d477 org.gnome.Boxes

**Comment by felipehw** [comment]
> > The problem, at least in my case, is with preexisting boxes.
> > If I create a new box, everything is OK.
> > There is a way to use the previous flatpak while this problem exists?
> > Thanks :)
> 
> downgrade:
> 
> sudo flatpak update --commit=36ce0e2c6efa0f5842f1675a157c062477d850e276ba6e35bb923ac702f0d477 org.gnome.Boxes

Owww! Incredible! Flatpak is a gem :) So versatile!

**Comment by felipeborges** [comment]
@felipehw btw, your issue seems slightly different than OP. It seems related to the dual-gpu setup. I have got my hands in a dual-gpu laptop to reproduce this issue and it is fixed once I blacklist/disable the dedicated GPU driver.

Obviously that's not a definitive solution, but it is a workaround.

**Comment by felipehw** [comment]
Thanks, @felipeborges. Do I need to create an issue specific for my case?

**Comment by felipeborges** [comment]
@felipehw no need. I am about to publish a fix that will workaround both issues.

**Comment by felipeborges** [comment]
I just pushed a new release that will offer an option to workaround the issues with 3D acceleration.

Please update, test, and REOPEN this issue if you still experience problems accessing your existing VMs or creating new ones.

**Comment by felipehw** [comment]
Hi, @felipeborges.
I got the new Gnome Boxes today and the problem remains.
I'm stuck with a black screen and I don't see an option to disable the 3D acceleration (i saw something like that in a printscreen from Gnome Boxes Twitter account).
How can I force Gnome Boxes to show the option to disable the 3D acceleration?
Thanks!

```
          ID: org.gnome.Boxes
         Ref: app/org.gnome.Boxes/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.32.0.1
     License: LGPL-2.1+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 497,5 MB
     Runtime: org.gnome.Platform/x86_64/3.30
         Sdk: org.gnome.Sdk/x86_64/3.30

      Commit: a2beee8d598f765af591ed8c47ffbfc48a7cd226e198d9d15b5cbe6c66fb7a56
      Parent: ccb29b388ddbb45b971fa8642ad1b527cd3da3675b5e5d783ba7a6c8e21a030a
     Subject: Update spice-gtk  and carry "cursor disappear" patches (1a1a30ec)
        Date: 2019-03-18 12:35:36 +0000
```

**Comment by felipehw** [comment]
Hi, @felipeborges .
I got some updated versions of Gnome Boxes and the problem remains.
I'm stuck with a black screen and I don't see an option to disable the 3D acceleration (i saw something like that in a printscreen from Gnome Boxes Twitter account).
How can I force Gnome Boxes to show the option to disable the 3D acceleration?
Thanks!
